set laststatus=2
call plug#begin('~/.vim/bundle')
    Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
    Plug 'junegunn/fzf.vim'
    Plug 'itchyny/lightline.vim'
    Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
    Plug 'w0rp/ale'
call plug#end()
map ; :Files<CR>
map <C-o> :NERDTreeToggle<CR>
