# function to return current branch name while suppressing errors.
function git_branch() {
    branch=$(git symbolic-ref HEAD 2> /dev/null | awk 'BEGIN{FS="/"} {print $NF}')
    if [[ $branch == "" ]]; then
        :
    else
        echo '\e[0;31m('$branch')\e[0m'
    fi
}

setopt prompt_subst             # allow command substitution inside the prompt
PROMPT=$'\e[0;33m$USER \e[0m%~$(git_branch)>'
